# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '28April.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtOpenGL

from gluttut import OpenGLEngine
from OpenGL.GL import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow") 
        MainWindow.resize(1429, 830) #window size
        self.centralwidget = QtWidgets.QWidget(MainWindow) #
        self.centralwidget.setObjectName("centralwidget") #

        self.openGLWidget = GlutTutWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(20, 10, 1221, 701)) #OpenGL window size
        self.openGLWidget.setObjectName("openGLWidget")

        self.x_vertical_slider = QtWidgets.QSlider(self.centralwidget) #
        self.x_vertical_slider.setGeometry(QtCore.QRect(1380, 180, 21, 441)) #
        self.x_vertical_slider.setOrientation(QtCore.Qt.Vertical) #
        self.x_vertical_slider.setObjectName("x_vertical_slider") #
        self.x_vertical_slider.setMinimum(0)
        self.x_vertical_slider.setMaximum(360)
        self.x_vertical_slider.valueChanged.connect(self.x_rotation_event)

        self.y_vertical_slider = QtWidgets.QSlider(self.centralwidget) #
        self.y_vertical_slider.setGeometry(QtCore.QRect(1340, 180, 21, 441)) #
        self.y_vertical_slider.setOrientation(QtCore.Qt.Vertical) #
        self.y_vertical_slider.setObjectName("verticalSlider_2") #
        self.y_vertical_slider.valueChanged.connect(self.y_rotation_event)
        self.y_vertical_slider.setMaximum(360)
        self.y_vertical_slider.setMinimum(0)

        self.z_vertical_slider = QtWidgets.QSlider(self.centralwidget) #
        self.z_vertical_slider.setGeometry(QtCore.QRect(1300, 180, 21, 441)) #
        self.z_vertical_slider.setOrientation(QtCore.Qt.Vertical) #
        self.z_vertical_slider.setObjectName("verticalSlider_3") #
        self.z_vertical_slider.valueChanged.connect(self.z_rotation_event)
        self.z_vertical_slider.setMaximum(360)
        self.z_vertical_slider.setMinimum(0)

        self.x_label = QtWidgets.QLabel(self.centralwidget) #
        self.x_label.setGeometry(QtCore.QRect(1300, 630, 21, 16)) #
        self.x_label.setObjectName("x_label") #

        self.y_label = QtWidgets.QLabel(self.centralwidget) #
        self.y_label.setGeometry(QtCore.QRect(1350, 630, 21, 16)) #
        self.y_label.setObjectName("y_label") #

        self.z_label = QtWidgets.QLabel(self.centralwidget) #
        self.z_label.setGeometry(QtCore.QRect(1390, 630, 21, 16)) #
        self.z_label.setObjectName("z_label") #

        self.rotation_label = QtWidgets.QLabel(self.centralwidget)
        self.rotation_label.setGeometry(QtCore.QRect(1320, 150, 60, 16))
        self.rotation_label.setObjectName("rotation_label")

        self.zoom_label = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_label.setGeometry(QtCore.QRect(1290, 30, 113, 32))
        self.zoom_label.setObjectName("zoom_label")

        self.stretch_label = QtWidgets.QPushButton(self.centralwidget)
        self.stretch_label.setGeometry(QtCore.QRect(1290, 60, 113, 32))
        self.stretch_label.setObjectName("stretch_label")

        self.scale_label = QtWidgets.QPushButton(self.centralwidget)
        self.scale_label.setGeometry(QtCore.QRect(1290, 90, 113, 32))
        self.scale_label.setObjectName("scale_label")

        self.mouse_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.mouse_radio_button.setGeometry(QtCore.QRect(1280, 680, 99, 20))
        self.mouse_radio_button.setObjectName("mouse_radio_button")

        self.hand_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.hand_radio_button.setGeometry(QtCore.QRect(1280, 700, 121, 20))
        self.hand_radio_button.setObjectName("radioButton_2")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1429, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow) #
        QtCore.QMetaObject.connectSlotsByName(MainWindow) #

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate #
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow")) #

        self.x_label.setText(_translate("MainWindow", "X"))
        self.y_label.setText(_translate("MainWindow", "Y"))
        self.z_label.setText(_translate("MainWindow", "Z"))
        self.rotation_label.setText(_translate("MainWindow", "Rotation:"))
        self.zoom_label.setText(_translate("MainWindow", "Zoom"))
        self.stretch_label.setText(_translate("MainWindow", "Strech"))
        self.scale_label.setText(_translate("MainWindow", "Scale"))
        self.mouse_radio_button.setText(_translate("MainWindow", "Mouse"))
        self.hand_radio_button.setText(_translate("MainWindow", "Hand gestures"))

    def x_rotation_event(self):
        deg = self.x_vertical_slider.value()
        self.openGLWidget.openGlEngine.rotate_yz(deg)
        self.openGLWidget.update()

    def y_rotation_event(self):
        deg = self.y_vertical_slider.value()
        self.openGLWidget.openGlEngine.rotate_xz(deg)
        self.openGLWidget.update()
    
    def z_rotation_event(self):
        deg = self.z_vertical_slider.value()
        self.openGLWidget.openGlEngine.rotate_xy(deg)
        self.openGLWidget.update()


class GlutTutWidget(QtOpenGL.QGLWidget):

    visible = False

    def __init__(self, parent=None):
        self.glformat = QtOpenGL.QGLFormat()
        self.glformat.setVersion(3, 3)
        self.glformat.setProfile(QtOpenGL.QGLFormat.CoreProfile)
        self.glformat.setSampleBuffers(True)
        super(GlutTutWidget, self).__init__(self.glformat)
        self.setParent(parent)
        # self.setMinimumSize(400, 400)
        self.openGlEngine = None

    def initializeGL(self):
        print(self.format())
        self.openGlEngine = OpenGLEngine()
        # self.context().device().
        
    def showEvent(self, a0):
        self.visible = True

    def paintGL(self):
        size = self.size()
        self.openGlEngine.framebuffer.update_dimensions(size.width(),
                                                        size.height())
        self.openGlEngine.render_scene()


    def resizeGL(self, w: int, h: int):
        self.openGlEngine.framebuffer.update_dimensions(w,h)
        glViewport(0, 0, w, h);
        return super().resizeGL(w, h)

    def minimumSizeHint(self):
        return QtCore.QSize(50, 50)

    def sizeHint(self):
        return QtCore.QSize(400, 400)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())